# https://github.com/grafana/grafana/blob/master/devenv/datasources.yaml  
apiVersion: 1

datasources:
  - name: elasticsearch
    type: elasticsearch
    access: proxy
    database: "[nginx.access-]YYYY.MM.DD"
    url: http://elasticsearch:9200
    jsonData:
      timeInterval: 10s
      interval: Daily
      timeField: "@timestamp"
      esVersion: 70
